# Generated by Django 2.1.7 on 2019-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='cityID')),
                ('city_name', models.CharField(max_length=50, verbose_name='cityName')),
            ],
            options={
                'verbose_name': 'cityMessage',
                'verbose_name_plural': 'cityMessage',
            },
        ),
        migrations.CreateModel(
            name='NetWorkSpeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(verbose_name='Speed')),
                ('city_left', models.IntegerField(verbose_name='cityLeft')),
                ('city_right', models.IntegerField(verbose_name='cityRight')),
            ],
            options={
                'verbose_name': 'cityMessage',
                'verbose_name_plural': 'cityMessage',
            },
        ),
    ]
